### ISSUE TITLE
Process_Fifa_18_Data

### ISSUE THREAD

**Issue by mdrmuhaimin** [mdrmuhaimin/ML_726_Project#2]
Fifa 18 Player Dataset
https://www.kaggle.com/kevinmh/fifa-18-more-complete-player-dataset/data

From this table please only take the players whose `id` is in attached file fifa_api_id.csv

[fifa_api_id.csv.zip](https://github.com/mdrmuhaimin/ML_726_Project/files/1509537/fifa_api_id.csv.zip)

**Comment by vladymyrkozyr** [comment]
Finished preprocessing
